name: Changed

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: authenticate git
        run: |
          git config --global user.Name "github-actions[bot]"
          git config --global user.Email "github-actions[bot]@users.noreply.github.com"
      - name: add change
        shell: pwsh
      
        run: |
          $OldContent = Get-Content ./CHANGELOG
          echo "$OldContent`n${{ github.event.commits[0].message }} - diff: https://github.com?Tyler887/WebGet/commit/main/${{ github.sha }}" > ./CHANGELOG
      - run: |
         git add ./CHANGELOG
         git commit -m "change $GITHUB_SHA"
      - run: |
          git pull https://github.com/${{github.repository}}.git --no-rebase
          git push
