name: Changed

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: authenticate git
        run: |
          git config --global user.Name "github-actions[bot]"
          git config --global user.Email "github-actions[bot]@users.noreply.github.com"
      - name: add change
        shell: pwsh
      
        run: |
          $OldContent = Get-Content ./README.md
          echo "$OldContent<br />https://github.com?Tyler887/WebGet/commit/main/$GITHUB_SHA" > ./README.md
      - run: |
         git add ./README.md
         git commit -m "change $GITHUB_SHA"
      - run: git push
