name: Translate README

on:

  push:

    branches:

      - main

      - master

jobs:
  
  build:
    name: "Translate to ${{ matrix.lang }}"
    runs-on: docker
    strategy:
      fail-fast: false
      matrix:
        lang: ["zh-CN", "zh-TW", "ja", "ar", "hi", "ko"]
       
    steps:

      - uses: actions/checkout@v2

      - name: Setup Node.js

        uses: actions/setup-node@v1

        with:

          node-version: 16.x

      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages  

      - name: Adding README - ${{ matrix.lang }}

        uses: dephraiim/translate-readme@main

        with:

          LANG: ${{ matrix.lang }}

      
